/**
 * Copyright (C) The software Authors. All rights reserved.
 * File Name: bypass/base_worker.cpp
 * Author:
 * mail:
 * Created Time: Thu Sep 25 01:13:06 2025
MOD: Adding new class for worker.* Brief:
 */
#include "base_worker.h"
#include "config.h"

bool BaseProcess::InitResource() {
    // Register a timestamp dynamic field.
    // m_attachDataQueue = new DynaQueue();
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    // buffer created by a primary application.
    // if (!m_attachDataQueue->attach_ring(ringname)) {
    if (!m_dataPool.attach_pool(KDataPoolName)) {
        spdlog::error("Attaching data pool {} failed!", KDataPoolName);
        exit(1);
    } else {
        spdlog::info("Pool attached: {}", KDataPoolName);
    }

    if (!m_dataRing.attach_ring(KDataRingName)) {
        spdlog::error("Attaching data ring {} failed!", KDataRingName);
        exit(1);
    } else {
        spdlog::info("Ring attached: {}", KDataRingName);
    }

    if (!m_cmdPool.attach_pool(KCmdPoolName)) {
        spdlog::error("Attaching cmd pool {} failed!", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Pool attached: {}", KCmdPoolName);
    }

    if (!m_cmdRing.attach_ring(KCmdRingName)) {
        spdlog::error("Attaching ring buffer {} failed!", KCmdRingName);
        exit(1);
    } else {
        spdlog::info("Ring attached: {}", KCmdRingName);
    }

    return true;
}


