#include "io_worker.h"

#include <stdint.h>
#include <sys/timerfd.h>
#include <unistd.h>

#include <thread>

const std::string KDataPoolName = "DataPool_0";
const std::string KDataRingName = "DataRing_0";

const std::string KCmdPoolName = "CmdPool_0";
const std::string KCmdRingName = "CmdRing_0";

std::string get_current_data_time() {
    // Example of the very popular RFC 3339 format UTC time
    std::time_t time = std::time({});
    char timeString[std::size("yyyy-mm-ddThh:mm:ssZ")];
    std::strftime(std::data(timeString), std::size(timeString), "%FT%TZ",
                  std::gmtime(&time));
    return timeString;
}

volatile sig_atomic_t exit_indicator = 0;

std::atomic<int> counter(0);

void timerThread(void *pstats) {
    int tfd = timerfd_create(CLOCK_MONOTONIC, 0);
    if (tfd == -1) {
        return;
    }

    itimerspec new_value{};
    new_value.it_interval.tv_sec = 1;  // Trigger interval: 1 second
    new_value.it_value.tv_sec = 1;     // For the next trigger.
    timerfd_settime(tfd, 0, &new_value, nullptr);

    while (!exit_indicator) {
        uint64_t expirations;
        read(tfd, &expirations, sizeof(expirations));  // 阻塞直到定时器触发
        counter += expirations;
        if (pstats) {
            Stats *ps = static_cast<Stats *>(pstats);
            ps->Ticks();
        }
    }

    close(tfd);
}

bool IOProcess::InitPrimaryResource() {
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    if (!m_dataPool.create_pool(KDataPoolName, 1024 * 1024, 1024,
                                rte_socket_id())) {
        spdlog::error("Cannot create data pool:{}!", KDataPoolName);
        exit(1);
    } else {
        spdlog::info("Primary process init pool: {}", KDataPoolName);
    }

    if (!m_dataRing.create_ring(KDataRingName, 512 * 1024, rte_socket_id())) {
        spdlog::error("Cannot create data ring:{}!", KDataRingName);
        exit(1);
    } else {
        spdlog::info("Primary process init ring: {}", KDataRingName);
    }

    // CmdPool: 1024 buffers, 512 bytes per buffer
    if (!m_cmdPool.create_pool(KCmdPoolName, 1024, 512, rte_socket_id())) {
        spdlog::error("Cannot create cmd pool:{}!", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Primary process init pool: {}", KCmdPoolName);
    }

    if (!m_cmdRing.create_ring(KCmdRingName, 512 * 1024, rte_socket_id())) {
        spdlog::error("Cannot create cmd ring:{}!", KCmdRingName);
        exit(1);
    } else {
        spdlog::info("Primary process init ring: {}", KCmdRingName);
    }
    return true;
}

int IOProcess::scan_request_loop() {
    while (!exit_indicator) {
        rte_mbuf *cmd_packets[32];
        // Check for any incoming packets in the ring buffer. We try to
        // dequeue max 32 packets at max at a time.
        uint8_t cmd_count = m_cmdRing.consume_packets(cmd_packets, 1);
        if (cmd_count > 0) {
            rte_pktmbuf_free(cmd_packets[0]);
            break;
        } else {
            spdlog::info("Waiting for the nic thread");
            sleep(1);
        }
    }
    return 1;
}
int IOProcess::io_loop() {
    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).

    std::cout
        << "Starting packet generation routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    // dataStats.Init();
    std::thread st(timerThread, &this->dataStats);
    while (!exit_indicator) {
        using namespace std::literals;
        // std::this_thread::sleep_for(1ms);

        // rte_mbuf *const packet = m_dataPool->allocate_mbuf();
        rte_mbuf *const packet = m_dataPool.allocate_mbuf();
        if (!packet) {
            continue;
        }

        this->write_packet(packet);

        // Enqueuing the packet in the ring buffer.
        if (m_dataRing.produce_packets(packet, 1)) {
            dataStats.totalCount++;
            // if (!(dataStats.totalCount % 1000)) {
            // std::cout << "Enqueued packet(s) in the ring. total :" <<
            // dataStats.totalCount << std::endl;
            // }
        } else {
            // std::cerr << "Space is full. "<< std::endl;
            rte_pktmbuf_free(packet);
        }
    }
    st.join();

    std::cout << "Total packets generated: " << dataStats.totalCount
              << std::endl;
    std::cout << "Exiting packet generation routine. " << std::endl;
    return 0;
}

void IOProcess::write_packet(rte_mbuf *packet) {
    // Timestamp the memory buffer (packet). The timestamp will be written in
    // the head room of the memory buffer. Head room is the memory area before
    // actual data room.
    static timespec ts{0};
    clock_gettime(CLOCK_REALTIME, &ts);
    *(RTE_MBUF_DYNFIELD(packet,
                        m_dataQueue.get_offset() /*timestamp_dynfield_offset*/,
                        uint64_t *)) = ((ts.tv_sec * 1000000000L) + ts.tv_nsec);

    // Filling some data in the packet.
    static const char data[] = "A quick brown fox jumps over the lazy dog.";
    uint8_t *const data_ptr = rte_pktmbuf_mtod(packet, uint8_t *);
    std::memcpy(data_ptr, data, sizeof(data));
    packet->data_len = sizeof(data);
}

bool NicProcess::InitNicResource() {
    // Register a timestamp dynamic field.
    // m_attachDataQueue = new DynaQueue();
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    // buffer created by a primary application.
    // if (!m_attachDataQueue->attach_ring(ringname)) {
    if (!m_dataRing.attach_ring(KDataRingName)) {
        spdlog::error("Attaching data ring {} failed!", KDataRingName);
        exit(1);
    } else {
        spdlog::info("Ring attached: {}", KDataRingName);
    }

    if (!m_cmdPool.attach_pool(KCmdPoolName)) {
        spdlog::error("Attaching cmd pool {} failed!", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Pool attached: {}", KCmdPoolName);
    }

    if (!m_cmdRing.attach_ring(KCmdRingName)) {
        spdlog::error("Attaching ring buffer {} failed!", KCmdRingName);
        exit(1);
    } else {
        spdlog::info("Ring attached: {}", KCmdRingName);
    }

    return true;
}

void NicProcess::issue_request() {
    rte_mbuf *const packet = m_cmdPool.allocate_mbuf();
    if (!packet) {
        spdlog::error("Failed to allocate mbuf from cmd pool {}", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Cmd buf created on {}.", KCmdRingName);
    }
    if (!m_cmdRing.produce_packets(packet, 1)){
        spdlog::info("Cmd Ring full: {}", KCmdRingName);
        rte_pktmbuf_free(packet);
    }
}

int NicProcess::recv_loop() {
    rte_mbuf *rx_packets[32];
    uint8_t rx_count = 0;
    uint64_t total_rx_packets = 0;
    uint64_t lastTimestamp = 0;

    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).
    std::cout
        << "Starting packet processing routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    issue_request();

    // Now continuously monitor the ring buffer for any incoming packets.
    while (!exit_indicator) {
        // Check for any incoming packets in the ring buffer. We try to
        // dequeue max 32 packets at max at a time.
        rx_count = m_dataRing.consume_packets(rx_packets, 1);

        if (!rx_count) {
            // No packets are present in ring buffer. Check again.
            // using namespace std::literals;
            // std::this_thread::sleep_for(50us);
            continue;
        }

        // Packets received. Now we will process them.
        for (uint8_t i = 0; i < rx_count; i++) {
            total_rx_packets++;
            rte_mbuf *const packet = rx_packets[i];

            // Get the timestamp of the received memory buffer (packet).
            const uint64_t timestamp = *(RTE_MBUF_DYNFIELD(
                packet, m_attachDataQueue.get_offset(), uint64_t *));

            if (!(total_rx_packets % 10000)) {
                uint8_t *data = rte_pktmbuf_mtod(packet, uint8_t *);
                printf("packet @ %lu data: %s \n", total_rx_packets, data);
            }

            if (timestamp < lastTimestamp) {
                std::cerr << get_current_data_time()
                          << " The received timestamp is less than last "
                             "time stamp. "
                          << lastTimestamp << ":" << timestamp << ":"
                          << packet->data_len << ":" << packet << std::endl;
            }

            lastTimestamp = timestamp;
            rte_pktmbuf_free(packet);
        }
    }

    spdlog::info("Total packets received: {}",total_rx_packets);
    return 0;
}
