#include "io_worker.h"

const std::string KDataRingName = "DataRing_0";
const std::string KDataPoolName = "DataPool_0";

std::string get_current_data_time() {
    // Example of the very popular RFC 3339 format UTC time
    std::time_t time = std::time({});
    char timeString[std::size("yyyy-mm-ddThh:mm:ssZ")];
    std::strftime(std::data(timeString), std::size(timeString), "%FT%TZ",
            std::gmtime(&time));
    return timeString;
}

volatile sig_atomic_t exit_indicator = 0;

bool IOProcess::InitPrimaryResource() {
    // Register a timestamp dynamic field.
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    // buffer created by a primary application.
    if (!m_dataPool.create_pool(KDataPoolName, rte_socket_id())) {
        printf_error("Cannot create pool:%s!\n", KDataPoolName.c_str());
        exit(1);
    }

    if (!m_dataRing.create_ring(KDataRingName, 512, rte_socket_id())) {
        printf_error("Cannot create ring:%s \n", KDataRingName.c_str());
        exit(1);
    }
    printf_error("IOProcess create ring %s done!\n", KDataRingName.c_str());
    return true;
}

int IOProcess::IO_loop() {
    uint8_t tx_count = 0;
    uint64_t total_tx_packets = 0;

    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).
    std::cout
        << "Starting packet generation routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    // Now continuously generate the packets and enqueue it in the ring
    // buffer.
    while (!exit_indicator) {
        using namespace std::literals;
        std::this_thread::sleep_for(10ms);

        //rte_mbuf *const packet = m_dataPool->allocate_mbuf();
        rte_mbuf *const packet = m_dataPool.allocate_mbuf();
        if (!packet) {
            continue;
        }

        this->write_packet(packet);

        // Enqueuing the packet in the ring buffer.
        if (m_dataRing.produce_packets(packet, 1)) {
            total_tx_packets++;
            if (!(total_tx_packets % 100)) {
                std::cout << "Successfully enqueued packet(s) in the ring "
                    "buffer. total packet: "
                    << total_tx_packets << std::endl;
            }
        } else {
            std::cerr << "Unable to enqueue packet in the ring buffer. "
                "Space is full. "
                << std::endl;
            // rte_pktmbuf_free(packet);
        }
    }

    std::cout << "Total packets generated: " << total_tx_packets
        << std::endl;
    std::cout << "Exiting packet generation routine. " << std::endl;
    return 0;
}

void IOProcess::write_packet(rte_mbuf *packet) {
    // Timestamp the memory buffer (packet). The timestamp will be written in
    // the head room of the memory buffer. Head room is the memory area before
    // actual data room.
    static timespec ts{0};
    clock_gettime(CLOCK_REALTIME, &ts);
    *(RTE_MBUF_DYNFIELD(packet,
                m_dataQueue.get_offset() /*timestamp_dynfield_offset*/,
                uint64_t *)) = ((ts.tv_sec * 1000000000L) + ts.tv_nsec);

    // Filling some data in the packet.
    static const char data[] = "A quick brown fox jumps over the lazy dog.";
    uint8_t *const data_ptr = rte_pktmbuf_mtod(packet, uint8_t *);
    std::memcpy(data_ptr, data, sizeof(data));
    packet->data_len = sizeof(data);
}

bool NicProcess::InitNicResource() {
    // Register a timestamp dynamic field.
    // m_attachDataQueue = new DynaQueue();
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    // buffer created by a primary application.
    //if (!m_attachDataQueue->attach_ring(ringname)) {
    if (!m_dataRing.attach_ring(KDataRingName)) {
        printf_error("Attaching ring buffer %s failed!\n",
                KDataRingName.c_str());
        exit(1);
    }
    printf_error("NicProcess create ringbuffer %s done!\n", KDataRingName.c_str());
    return true;
}
int NicProcess::CMD_loop() {
    rte_mbuf *rx_packets[32];
    uint8_t rx_count = 0;
    uint64_t total_rx_packets = 0;
    uint64_t lastTimestamp = 0;

    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).
    std::cout
        << "Starting packet processing routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    // Now continuously monitor the ring buffer for any incoming packets.
    while (!exit_indicator) {
        // Check for any incoming packets in the ring buffer. We try to
        // dequeue max 32 packets at max at a time.
        rx_count = m_dataRing.consume_packets(rx_packets, 1);

        if (!rx_count) {
            // No packets are present in ring buffer. Check again.
            using namespace std::literals;
            std::this_thread::sleep_for(50us);
            continue;
        }

        // Packets received. Now we will process them.
        for (uint8_t i = 0; i < rx_count; i++) {
            total_rx_packets++;
            rte_mbuf *const packet = rx_packets[i];

            // Get the timestamp of the received memory buffer (packet).
            const uint64_t timestamp = *(RTE_MBUF_DYNFIELD(
                        packet,
                        m_attachDataQueue.get_offset() /*timestamp_dynfield_offset*/,
                        uint64_t *));

            if (!(total_rx_packets % 100)) {
                uint8_t *data = rte_pktmbuf_mtod(packet, uint8_t *);
                printf("packet @ %lu data: %s \n", total_rx_packets, data);
            }

            if (timestamp < lastTimestamp) {
                std::cerr << get_current_data_time()
                    << " The received timestamp is less than last "
                    "time stamp. "
                    << lastTimestamp << ":" << timestamp << ":"
                    << packet->data_len << ":" << packet << std::endl;
            }

            lastTimestamp = timestamp;
            rte_pktmbuf_free(packet);
        }
    }

    std::cout << "Total packets received: " << total_rx_packets
        << std::endl;
    std::cout << "Exiting packet processing routine. " << std::endl;
    return 0;
}
