#include "io_worker.h"

#include <stdint.h>
#include <sys/timerfd.h>
#include <unistd.h>

#include <cstring>
#include <ctime>

#include <thread>
#include "config.h"


std::string get_current_data_time() {
    // Example of the very popular RFC 3339 format UTC time
    std::time_t time = std::time({});
    char timeString[std::size("yyyy-mm-ddThh:mm:ssZ")];
    std::strftime(std::data(timeString), std::size(timeString), "%FT%TZ",
                  std::gmtime(&time));
    return timeString;
}


bool IOProcess::InitPrimaryResource() {
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    if (!m_dataPool.create_pool(KDataPoolName, 1024 * 1024, 1024,
                                rte_socket_id())) {
        spdlog::error("Cannot create data pool:{}!", KDataPoolName);
        exit(1);
    } else {
        spdlog::info("Primary process init pool: {}", KDataPoolName);
    }

    if (!m_dataRing.create_ring(KDataRingName, 512 * 1024, rte_socket_id())) {
        spdlog::error("Cannot create data ring:{}!", KDataRingName);
        exit(1);
    } else {
        spdlog::info("Primary process init ring: {}", KDataRingName);
    }

    // CmdPool: 1024 buffers, 512 bytes per buffer
    if (!m_cmdPool.create_pool(KCmdPoolName, 1024, 512, rte_socket_id())) {
        spdlog::error("Cannot create cmd pool:{}!", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Primary process init pool: {}", KCmdPoolName);
    }

    if (!m_cmdRing.create_ring(KCmdRingName, 512 * 1024, rte_socket_id())) {
        spdlog::error("Cannot create cmd ring:{}!", KCmdRingName);
        exit(1);
    } else {
        spdlog::info("Primary process init ring: {}", KCmdRingName);
    }
    return true;
}

int IOProcess::scan_request_loop() {
    while (!exit_indicator) {
        rte_mbuf *cmd_packets[32];
        // Check for any incoming packets in the ring buffer. We try to
        // dequeue max 32 packets at max at a time.
        uint8_t cmd_count = m_cmdRing.consume_packets(cmd_packets, 1);
        if (cmd_count > 0) {
            rte_pktmbuf_free(cmd_packets[0]);
            break;
        } else {
            spdlog::info("Waiting for the nic thread");
            sleep(1);
        }
    }
    return 1;
}
int IOProcess::io_loop() {
    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).

    std::cout
        << "Starting packet generation routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    // ioStats.Init();
    std::thread st(timerThread, &this->ioStats);
    while (!exit_indicator) {
        // using namespace std::literals;
        // std::this_thread::sleep_for(1ms);
        // rte_mbuf *const packet = m_dataPool->allocate_mbuf();
        rte_mbuf *const packet = m_dataPool.allocate_mbuf();
        if (!packet) {
            continue;
        }

        this->write_packet(packet);

        // Enqueuing the packet in the ring buffer.
        if (m_dataRing.produce_packets(packet, 1)) {
            ioStats.totalCount++;
            // if (!(ioStats.totalCount % 1000)) {
            // std::cout << "Enqueued packet(s) in the ring. total :" <<
            // ioStats.totalCount << std::endl;
            // }
        } else {
            // std::cerr << "Space is full. "<< std::endl;
            rte_pktmbuf_free(packet);
        }
    }
    st.join();

    std::cout << "Total packets generated: " << ioStats.totalCount
              << std::endl;
    std::cout << "Exiting packet generation routine. " << std::endl;
    return 0;
}

void IOProcess::write_packet(rte_mbuf *packet) {
    // Timestamp the memory buffer (packet). The timestamp will be written in
    // the head room of the memory buffer. Head room is the memory area before
    // actual data room.
    static timespec ts{0};
    clock_gettime(CLOCK_REALTIME, &ts);
    *(RTE_MBUF_DYNFIELD(packet,
                        m_dataQueue.get_offset() /*timestamp_dynfield_offset*/,
                        uint64_t *)) = ((ts.tv_sec * 1000000000L) + ts.tv_nsec);

    // Filling some data in the packet.
    static const char data[] = "A quick brown fox jumps over the lazy dog.";
    uint8_t *const data_ptr = rte_pktmbuf_mtod(packet, uint8_t *);
    std::memcpy(data_ptr, data, sizeof(data));
    packet->data_len = sizeof(data);
}


