// MIT License
//
// Copyright (c) 2024 Muhammad Awais Khalid
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include <csignal>
#include <cstring>
#include <ctime>
#include <iostream>
#include <queue>
#include <vector>

#include "bpbuf_utils.h"
#include "debug_utils.h"

const std::string io_owned_pool = "io_owned_pool_0";

volatile sig_atomic_t exit_indicator = 0;

ExchangeQueue *g_dataQueue;
ExchangeQueue *g_cmdQueue;

void terminate(int signal) { exit_indicator = 1; }

std::string get_current_data_time() {
    // Example of the very popular RFC 3339 format UTC time
    std::time_t time = std::time({});
    char timeString[std::size("yyyy-mm-ddThh:mm:ssZ")];
    std::strftime(std::data(timeString), std::size(timeString), "%FT%TZ",
                  std::gmtime(&time));
    return timeString;
}


class IOProcess {
public:
    bool InitIoResource(const std::string poolname,
                             const std::string ringname) {
        // Primary process with look up for the ring buffer and receive the
        // packets generated by primary DPDK application. Lookup for the ring
        // buffer created by a primary application.
        if (!g_dataQueue->create_pool(poolname, rte_socket_id())) {
            printf_error("Cannot create pool!\n");
            exit(1);
        }

        if (!g_dataQueue->create_ring(ringname, 512, rte_socket_id())) {
            printf_error("Cannot create ring!\n");
            exit(1);
        }
        std::cout << "Ring buffer creation successful against name: "
                  << ringname.c_str() << std::endl;
        return true;
    }

    int MainLoop() { return IO_loop(); }

    int IO_loop() {
        uint8_t tx_count = 0;
        uint64_t total_tx_packets = 0;

        // We will print the logical core id (CPU id) on which this thread is
        // going to be executed. rte_lcore_id() function will return the current
        // logical core id (CPU id).
        std::cout
            << "Starting packet generation routine. Logical core id (CPU id): "
            << rte_lcore_id() << std::endl;

        // Now continuously generate the packets and enqueue it in the ring
        // buffer.
        while (!exit_indicator) {
            using namespace std::literals;
            std::this_thread::sleep_for(10ms);

            rte_mbuf *const packet = g_dataQueue->allocate_mbuf();
            if (!packet) {
                continue;
            }

            this->write_packet(packet);

            // Enqueuing the packet in the ring buffer.
            // if (!rte_ring_enqueue(g_dataQueue->get_ring(), packet)) {
            if (g_dataQueue->produce_packets(packet)) {
                total_tx_packets++;
                if (!(total_tx_packets % 100)) {
                    std::cout << "Successfully enqueued packet(s) in the ring "
                                 "buffer. total packet: "
                              << total_tx_packets << std::endl;
                }
            } else {
                std::cerr << "Unable to enqueue packet in the ring buffer. "
                             "Space is full. "
                          << std::endl;
                // rte_pktmbuf_free(packet);
            }
        }

        std::cout << "Total packets generated: " << total_tx_packets
                  << std::endl;
        std::cout << "Exiting packet generation routine. " << std::endl;
        return 0;
    }

private:

    void write_packet(rte_mbuf *packet) {
        // Timestamp the memory buffer (packet). The timestamp will be written in
        // the head room of the memory buffer. Head room is the memory area before
        // actual data room.
        static timespec ts{0};
        clock_gettime(CLOCK_REALTIME, &ts);
        *(RTE_MBUF_DYNFIELD(packet,
                    g_dataQueue->get_offset() /*timestamp_dynfield_offset*/,
                    uint64_t *)) = ((ts.tv_sec * 1000000000L) + ts.tv_nsec);

        // Filling some data in the packet.
        static const char data[] = "A quick brown fox jumps over the lazy dog.";
        uint8_t *const data_ptr = rte_pktmbuf_mtod(packet, uint8_t *);
        std::memcpy(data_ptr, data, sizeof(data));
        packet->data_len = sizeof(data);
    }
    std::queue<int> tasks;
};

class NicProcess {
public:
    bool InitNicResource(const std::string ringname) {
        // Primary process with look up for the ring buffer and receive the
        // packets generated by primary DPDK application. Lookup for the ring
        // buffer created by a primary application.
        if (!g_dataQueue->attach_ring(ringname)) {
            printf_error("Attaching ring buffer %s failed!\n",
                         ringname.c_str());
            exit(1);
        }
        std::cout << "Ring buffer lookup successful against name: "
                  << ringname.c_str() << std::endl;
        return true;
    }
    int MainLoop() { return CMD_loop(); }
    int CMD_loop() {
        rte_mbuf *rx_packets[32];
        uint8_t rx_count = 0;
        uint64_t total_rx_packets = 0;
        uint64_t lastTimestamp = 0;

        // We will print the logical core id (CPU id) on which this thread is
        // going to be executed. rte_lcore_id() function will return the current
        // logical core id (CPU id).
        std::cout
            << "Starting packet processing routine. Logical core id (CPU id): "
            << rte_lcore_id() << std::endl;

        // Now continuously monitor the ring buffer for any incoming packets.
        while (!exit_indicator) {
            // Check for any incoming packets in the ring buffer. We try to
            // dequeue max 32 packets at max at a time.
            rx_count = g_dataQueue->consume_packets(rx_packets, 1);

            if (!rx_count) {
                // No packets are present in ring buffer. Check again.
                using namespace std::literals;
                std::this_thread::sleep_for(50us);
                continue;
            }

            // Packets received. Now we will process them.
            for (uint8_t i = 0; i < rx_count; i++) {
                total_rx_packets++;
                rte_mbuf *const packet = rx_packets[i];

                // Get the timestamp of the received memory buffer (packet).
                const uint64_t timestamp = *(RTE_MBUF_DYNFIELD(
                    packet,
                    g_dataQueue->get_offset() /*timestamp_dynfield_offset*/,
                    uint64_t *));

                if (!(total_rx_packets % 100)) {
                    uint8_t *data = rte_pktmbuf_mtod(packet, uint8_t *);
                    printf("packet @ %lu data: %s \n", total_rx_packets, data);
                }

                if (timestamp < lastTimestamp) {
                    std::cerr << get_current_data_time()
                              << " The received timestamp is less than last "
                                 "time stamp. "
                              << lastTimestamp << ":" << timestamp << ":"
                              << packet->data_len << ":" << packet << std::endl;
                }

                lastTimestamp = timestamp;
                rte_pktmbuf_free(packet);
            }
        }

        std::cout << "Total packets received: " << total_rx_packets
                  << std::endl;
        std::cout << "Exiting packet processing routine. " << std::endl;
        return 0;
    }

private:
    uint64_t m_total_rx_packets = 0;
};

int main(int argc, char **argv) {
    // Setting up signals to catch TERM and INT signal.
    struct sigaction action;
    memset(&action, 0, sizeof(struct sigaction));
    action.sa_handler = terminate;
    sigaction(SIGTERM, &action, nullptr);
    sigaction(SIGINT, &action, nullptr);

    // 1)
    // Initializing the DPDK EAL (Environment Abstraction Layer). This is the
    // first step of a DPDK program before we call any further DPDK API. The
    // arguments passed to this programs are passed to rte_eal_init() DPDK API.
    // A user must pass DPDK EAL arguments before the application arguments. The
    // DPDK EAL arguments and application arguments must be separated by '--'.
    // For example: ./<dpdk_application> --lcores=0,1 -n 4 -- -s 1 -t 2. `--`
    // will tell the rte_eal_init() that all the DPDK EAL arguments are present
    // before this. In the above example the DPDK EAL arguments are --lcores and
    // -n. The user arguments are -s and -t. DPDK EAL argument `--lcores=0,1`
    // means that there are two logical cores (CPUs) assigned to this DPDK
    // application. The first logical core is 0 and second is 1. DPDK
    // application will launch total_logical_cores worker threads in the
    // application (including main) So in the above example, the DPDK
    // application has two logical cores (0,1). The main function will run on
    // first logical core (0) and an additional worker thread will be launched
    // on the next logical core (1). A DPDK application sets the affinity of
    // execution threads to specific logical cores to achieve performance.
    // DPDK EAL argument `-n 4` means that this DPDK application uses 4 memory
    // channels. The details are DPDK EAL arguments is present at:
    // https://doc.dpdk.org/guides/linux_gsg/linux_eal_parameters.html
    int32_t return_val = rte_eal_init(argc, argv);
    if (return_val < 0) {
        log_error("EAL:", "Unable to initialize DPDK EAL. Error code: %d\n",
                  rte_errno);
        exit(1);
    }

    // rte_eal_init() DPDK API will return the number of DPDK EAL arguments
    // processed. So we will subtract the number of DPDK EAL arguments from the
    // total arguments and point argv to the first user argument. For example:
    // ./<dpdk_application> --lcores=0 -n 4 -- -s 1 -t 2 rte_eal_init() will
    // return 4. The total arguments passed to this program is 9. So after
    // subtracting the actual user arguments is (9 - 4 = 5). Setting `argv` to
    // point to the start of user argument which is `--`
    argc -= return_val;
    argv += return_val;

    if (argc < 2) {
        bypass_log_error(
            "Ring buffer name not provided in command line arguments.\n");
        rte_eal_cleanup();
        exit(1);
    }

    std::string data_ring_name = argv[1];
    if (data_ring_name.empty()) {
        bypass_log_error("Ring buffer name is empty.");
        rte_eal_cleanup();
        exit(1);
    }

    // Detecting the logical cores (CPUs) ids passed to this DPDK application.
    uint16_t i = 0;
    std::vector<uint16_t> logicalCores;
    log_info("bypass:", "Logical cores ids (CPU ids): ");
    RTE_LCORE_FOREACH(i) {
        logicalCores.push_back(i);
        log_info(" ", "%d", i);
    }
    log_info("", "\n");

    // We must have atleast one logical cores passed as an argument to this DPDK
    // application.
    if (logicalCores.size() != 1) {
        log_error(
            "EAL:",
            "One logical core is required to run this DPDK application.\n");
        rte_eal_cleanup();
        exit(1);
    }

    // Register a timestamp dynamic field.
    g_dataQueue = new ExchangeQueue();

    // Find the process type of current process. primary/secondary.
    const rte_proc_type_t proc_type = rte_eal_process_type();

    if (proc_type == RTE_PROC_PRIMARY) {
        IOProcess ioProcess;
        ioProcess.InitIoResource(io_owned_pool, data_ring_name);

        // Start packet generation routine.
        ioProcess.MainLoop();
        using namespace std::literals;
        std::this_thread::sleep_for(500ms);
    } else if (proc_type == RTE_PROC_SECONDARY) {
        NicProcess nicProcess;
        nicProcess.InitNicResource(data_ring_name);

        // Start receiving and processing the packets.
        nicProcess.MainLoop();
    }

    delete g_dataQueue;

    log_info("DPDK", "Exiting DPDK program ... ");
    rte_eal_cleanup();
    return 0;
}
