/**
 * Copyright (C) The software Authors. All rights reserved.
 * File Name: bypass/mem_worker.cpp
 * Author:
 * mail:
 * Created Time: Wed Sep 24 05:20:14 2025
 * Brief:
 */
#include "nic_worker.h"
#include "config.h"

bool NicProcess::InitNicResource() {
    // Register a timestamp dynamic field.
    // m_attachDataQueue = new DynaQueue();
    // Primary process with look up for the ring buffer and receive the
    // packets generated by primary DPDK application. Lookup for the ring
    // buffer created by a primary application.
    // if (!m_attachDataQueue->attach_ring(ringname)) {

    InitResource();
    return initnicport();
}

bool NicProcess::initnicport(){
    uint16_t port_ids[RTE_MAX_ETHPORTS] = {0};
    int16_t id = 0;
    int16_t total_port_count = 0;

    // Detecting the available ports (ethernet interfaces) in the system.
    RTE_ETH_FOREACH_DEV(id) {
        port_ids[total_port_count] = id;
        total_port_count++;
        if (total_port_count >= RTE_MAX_ETHPORTS)
        {
            spdlog::info("Total number of detected ports exceeds RTE_MAX_ETHPORTS.");
            rte_eal_cleanup();
            exit(1);
        }
    }
    return true;
}

void NicProcess::issue_request() {
    rte_mbuf *const packet = m_cmdPool.allocate_mbuf();
    if (!packet) {
        spdlog::error("Failed to allocate mbuf from cmd pool {}", KCmdPoolName);
        exit(1);
    } else {
        spdlog::info("Cmd buf created on {}.", KCmdRingName);
    }
    if (!m_cmdRing.produce_packets(packet, 1)){
        spdlog::info("Cmd Ring full: {}", KCmdRingName);
        rte_pktmbuf_free(packet);
    }
}

int NicProcess::recv_loop() {
    rte_mbuf *rx_packets[32];
    uint8_t rx_count = 0;
    uint64_t total_rx_packets = 0;
    uint64_t lastTimestamp = 0;

    // We will print the logical core id (CPU id) on which this thread is
    // going to be executed. rte_lcore_id() function will return the current
    // logical core id (CPU id).
    std::cout
        << "Starting packet processing routine. Logical core id (CPU id): "
        << rte_lcore_id() << std::endl;

    issue_request();

    std::thread st(timerThread, &this->nicStats);
    // Now continuously monitor the ring buffer for any incoming packets.
    while (!exit_indicator) {
        // Check for any incoming packets in the ring buffer. We try to
        // dequeue max 32 packets at max at a time.
        rx_count = m_dataRing.consume_packets(rx_packets, 1);

        if (!rx_count) {
            // No packets are present in ring buffer. Check again.
            // using namespace std::literals;
            // std::this_thread::sleep_for(50us);
            continue;
        }

        // Packets received. Now we will process them.
        uint8_t done = 0;
        for (; done < rx_count; done++) {
            rte_mbuf *const packet = rx_packets[done];

            // Get the timestamp of the received memory buffer (packet).
/*
            const uint64_t timestamp = *(RTE_MBUF_DYNFIELD(
                packet, m_attachDataQueue.get_offset(), uint64_t *));

            if (!(total_rx_packets % 10000)) {
                uint8_t *data = rte_pktmbuf_mtod(packet, uint8_t *);
                printf("packet @ %lu data: %s \n", total_rx_packets, data);
            }
            if (timestamp < lastTimestamp) {
                std::cerr << get_current_data_time()
                          << " The received timestamp is less than last "
                             "time stamp. "
                          << lastTimestamp << ":" << timestamp << ":"
                          << packet->data_len << ":" << packet << std::endl;
            }
            lastTimestamp = timestamp;
*/
            rte_pktmbuf_free(packet);
        }
        nicStats.totalCount+= done;
    }
    st.join();

    spdlog::info("Total packets received: {}",total_rx_packets);
    return 0;
}
